/**
 * Chronicle — World book operations
 * Creates/manages Chronicle world books and lorebook entries.
 */

declare const spindle: import('lumiverse-spindle-types').SpindleAPI

const LOG = '[Chronicle:Worker]'

// ── Spindle API Return Types ────────────────────────────────────────

export interface WorldBookDTO {
  id: string
  name: string
  description?: string
}

interface WorldBookEntryDTO {
  id: string
  key: string[]
  content: string
  comment?: string
  created_at: number
}

// ── World book entry creation ──────────────────────────────────────

const CHRONICLE_WORLD_BOOK_NAME = 'Chronicle'

// Mutex for book creation to prevent race conditions when two concurrent
// requests both detect "no book" and both try to create one.
const _creationLocks = new Map<string, Promise<{ id: string }>>()

export async function getOrCreateChronicleBook(userId: string): Promise<{ id: string }> {
  const key = `chronicle:${CHRONICLE_WORLD_BOOK_NAME}:${userId}`

  // If another request is already creating this book, wait for it
  const existing = _creationLocks.get(key)
  if (existing) return existing

  const promise = (async () => {
    const { data: books } = await Promise.race([
      spindle.world_books.list({ limit: 200, userId }) as Promise<{ data: WorldBookDTO[]; total: number }>,
      new Promise<never>((_, reject) =>
        setTimeout(() => reject(new Error('Timed out listing world books')), 10_000)
      ),
    ])
    const allBooks = books as WorldBookDTO[]
    const chronicleBook = allBooks.find((b) => b.name === CHRONICLE_WORLD_BOOK_NAME)

    if (chronicleBook) {
      return { id: chronicleBook.id }
    }

    const newBook = await Promise.race([
      spindle.world_books.create(
        { name: CHRONICLE_WORLD_BOOK_NAME, description: 'Lorebook entries generated by the Chronicle extension' },
        userId
      ) as Promise<WorldBookDTO>,
      new Promise<never>((_, reject) =>
        setTimeout(() => reject(new Error('Timed out creating world book')), 10_000)
      ),
    ])

    spindle.log.info(`${LOG} Created Chronicle world book: ${(newBook as WorldBookDTO).id}`)
    return { id: (newBook as WorldBookDTO).id }
  })()

  _creationLocks.set(key, promise)

  // Safety timeout — auto-release lock after 30s if the finally block doesn't run
  const safetyTimeout = setTimeout(() => _creationLocks.delete(key), 30_000)

  try {
    return await promise
  } finally {
    clearTimeout(safetyTimeout)
    _creationLocks.delete(key)
  }
}

/**
 * Creates the next available Chronicle_N book.
 * - Searches for existing books matching "Chronicle_N" (N = 1, 2, 3...)
 * - Skips the unnumbered "Chronicle" book created by getOrCreateChronicleBook
 * - Finds the highest N, creates Chronicle_{N+1}
 * - If no Chronicle_N books exist, creates "Chronicle_1"
 */
export async function autoGenerateChronicleBook(userId: string): Promise<{ id: string }> {
  // Use mutex to prevent two concurrent calls from computing the same N
  const key = `chronicle:auto_generate:${userId}`
  const existing = _creationLocks.get(key)
  if (existing) return existing

  const promise = (async () => {
    const { data: books } = await Promise.race([
      spindle.world_books.list({ limit: 200, userId }) as Promise<{ data: WorldBookDTO[]; total: number }>,
      new Promise<never>((_, reject) =>
        setTimeout(() => reject(new Error('Auto-generate lorebook list timed out')), 10_000)
      ),
    ])
    const allBooks = books as WorldBookDTO[]

    // Match "Chronicle_N" where N is digits — intentionally skips bare "Chronicle"
    const chronicleNumbers = allBooks
      .map((b) => b.name.match(/^Chronicle_(\d+)$/))
      .filter((m): m is RegExpMatchArray => m !== null)
      .map((m) => parseInt(m[1], 10))
      .sort((a, b) => a - b)

    const nextN = chronicleNumbers.length > 0 ? chronicleNumbers[chronicleNumbers.length - 1] + 1 : 1
    const bookName = `Chronicle_${nextN}`

    const newBook = await Promise.race([
      spindle.world_books.create(
        { name: bookName, description: `Auto-generated Chronicle lorebook #${nextN}` },
        userId
      ) as Promise<WorldBookDTO>,
      new Promise<never>((_, reject) =>
        setTimeout(() => reject(new Error('Timed out creating lorebook')), 10_000)
      ),
    ])

    spindle.log.info(`${LOG} Auto-generated Chronicle book: ${bookName} (${newBook.id})`)
    return { id: newBook.id }
  })()

  _creationLocks.set(key, promise)

  // Safety timeout — auto-release lock after 30s if the finally block doesn't run
  const safetyTimeout = setTimeout(() => _creationLocks.delete(key), 30_000)

  try {
    return await promise
  } finally {
    clearTimeout(safetyTimeout)
    _creationLocks.delete(key)
  }
}

/**
 * Find the next chronicle entry number for a world book by parsing
 * existing entry comments for leading numbers (e.g. "01 - Title | ...").
 * Returns "1" if no numbered entries found or listing fails.
 */
export async function resolveNextChronicleNumber(
  worldBookId: string,
  userId: string
): Promise<string> {
  try {
    const result = await spindle.world_books.entries.list(worldBookId, {
      limit: 500,
      userId,
    }) as { data: Array<{ comment?: string }>; total: number }

    let maxNum = 0
    for (const entry of result.data) {
      if (!entry.comment) continue
      // Match a number at the start of the comment,
      // optionally followed by " - " (the `{number} - {title}` format separator)
      const match = entry.comment.match(/^(\d+)(?:\s*-)?/)
      if (match) {
        const num = parseInt(match[1], 10)
        if (num > maxNum) maxNum = num
      }
    }
    return String(maxNum + 1)
  } catch (err) {
    spindle.log.warn(`${LOG} resolveNextChronicleNumber failed: ${err}`)
    return '1'
  }
}

/**
 * Fetches the most recent entries from the target world book and formats
 * them as compact context for the LLM. Returns empty string on failure or if no entries.
 *
 * The Spindle API returns entries sorted by order_value ASC, id ASC (oldest first).
 * We fetch a generous batch (500), extract scene numbers from comments, sort by
 * scene number descending, and take the top `count` entries.
 */
export async function fetchRecentSummaries(
  worldBookId: string,
  userId: string,
  count: number = 3
): Promise<string> {
  try {
    const result = await spindle.world_books.entries.list(worldBookId, {
      limit: 500,
      userId,
    }) as { data: Array<{ comment?: string; content?: string }> }

    if (!result.data.length) return ''

    // Extract scene number from comment, sort descending, take top N
    const withNumbers = result.data
      .map(entry => {
        const numMatch = entry.comment?.match(/^(\d+)(?:\s*-)?/)
        return {
          entry,
          sceneNum: numMatch ? parseInt(numMatch[1], 10) : 0,
        }
      })
      .sort((a, b) => b.sceneNum - a.sceneNum)
      .slice(0, count)

    const summaries = withNumbers.map(({ entry, sceneNum }) => {
      const sceneLabel = sceneNum > 0 ? `Scene ${sceneNum}` : 'Entry'
      const snippet = (entry.content ?? '').slice(0, 200).replace(/\n/g, ' ')
      return `${sceneLabel}: ${snippet}${entry.content && entry.content.length > 200 ? '…' : ''}`
    })

    return `\n\n<> Recent scene summaries (for continuity — the messages above follow these scenes):\n${summaries.map(s => `- ${s}`).join('\n')}`
  } catch (err) {
    spindle.log.warn(`${LOG} fetchRecentSummaries failed: ${err}`)
    return '' // Non-fatal — continue without context
  }
}

export async function saveLorebookEntry(
  summary: { title: string; content: string; keys: string[] },
  chatId: string,
  messageIds: string[],
  worldBookId: string | undefined,
  userId: string,
  entrySettings?: Record<string, unknown>,
  titleFormat?: string,
  sceneNumber?: string  // pre-resolved scene number from preview phase
): Promise<{ entryId: string; worldBookId: string }> {
  let targetBookId = worldBookId

  // Handle auto-generate: create Chronicle_N
  if (targetBookId === '__auto_generate__') {
    const book = await autoGenerateChronicleBook(userId)
    targetBookId = book.id
  }

  if (!targetBookId) {
    const book = await getOrCreateChronicleBook(userId)
    targetBookId = book.id
  }

  // Build the entry input from settings (settingsToCreateInput already produces snake_case API keys)
  const entryInput: Record<string, unknown> = { ...(entrySettings || {}) }

  // Use LLM auto-generated keys, or title-based fallback
  entryInput.key = (summary.keys && summary.keys.length > 0)
    ? summary.keys
    : [summary.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '_')
      .replace(/^_|_$/g, '')
      .slice(0, 50)]

  // Secondary keys not user-configurable
  entryInput.keysecondary = []

  // Override with actual content from summary
  entryInput.content = summary.content

  // Auto-generate source metadata with optional title format
  // Apply title format template to produce the entry's display name
  let displayName = summary.title
  if (titleFormat) {
    // Resolve {number} if the format uses it — reads existing entries to find n+1
    let resolvedFormat = titleFormat
    if (titleFormat.includes('{number}')) {
      const nextNum = sceneNumber ?? await resolveNextChronicleNumber(targetBookId, userId)
      resolvedFormat = titleFormat.replace(/\{number\}/g, nextNum)
    }
    const now = new Date()
    displayName = resolvedFormat
      .replace(/\{title\}/g, summary.title)
      .replace(/\{date\}/g, now.toLocaleDateString())
      .replace(/\{time\}/g, now.toLocaleTimeString())
  }
  // Use displayName (formatted title) as the leading part of the comment.
  // displayName is either the titleFormat-rendered string or the raw summary.title.
  entryInput.comment = `${displayName} | Chronicle summary | Source: chat ${chatId}, ${messageIds.length} messages | ${new Date().toISOString()}`

  // All remaining fields (key, keysecondary, comment, position, depth, role,
  // order_value, selective, constant, disabled, case_sensitive, match_whole_words,
  // use_regex, use_probability, vectorized, probability, scan_depth, selective_logic,
  // priority, sticky, cooldown, delay, prevent_recursion, exclude_recursion,
  // delay_until_recursion, group_name, group_weight, group_override, automation_id)
  // are valid CreateWorldBookEntryInput fields passed through from settings.

  const entry = await spindle.world_books.entries.create(
    targetBookId,
    entryInput,
    userId
  ) as WorldBookEntryDTO

  return {
    entryId: entry.id,
    worldBookId: targetBookId,
  }
}
